services:
    pgdatabase:
        image: postgres:13
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: taxi_db
        ports:
            - 5432:5432
        volumes:
            - ./pgdata:/var/lib/postgresql/data:rw
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - 8080:80
        volumes:
            - ./pgadmin:/var/lib/pgadmin:rw
